---
name: Lint general

on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  oxlint:
    name: Oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: mise run lint

  typecheck:
    name: Type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type-check
        run: mise run typecheck

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting
        run: mise run format:check

  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@6d0087dcfd2e05578eff9ca03359dbcb876d7fba # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@6d0087dcfd2e05578eff9ca03359dbcb876d7fba # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@6d0087dcfd2e05578eff9ca03359dbcb876d7fba # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@6d0087dcfd2e05578eff9ca03359dbcb876d7fba # master
